version: '3'
services:
  wordpress:
    image: wordpress:latest
    hostname: wordpress
    ports:
      - '80:80'
    restart: unless-stopped
    volumes:
      - ./wp-config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/languages:/var/www/html/wp-content/languages
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
    - '3306:3306'
    restart: unless-stopped
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
     MYSQL_DATABASE: wordpress
     MYSQL_ROOT_PASSWORD: wordpress
     MYSQL_USER: root
     MYSQL_PASSWORD: wordpress

volumes:
  wp-data:
