version: '3.8'
services:

  laravel:
    build: 
      context: .
      dockerfile: Dockerfile
    image: php:latest
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - lnm
      
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports: 
      - '80:80'
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - lnm
      
  mysql:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lnm
      
 networks:
   lnm:
     driver: bridge  
 # To be able to use this volume across services
 volumes:
   dbdata:
     driver: local
