version: '2.2'
services:
  es-master:
    build: .
    container_name: es-master
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /DATA3:/DATA3/elasticsearch
      - ./config/elasticsearch-master.yml:/etc/elasticsearch/elasticsearch.yml
      - ./config/jvm.options-master:/etc/elasticsearch/jvm.options
      - config-es-master:/etc/elasticsearch
    ports:
      - 9200:9200
    networks:
      - elk
  es-node-1:
    build: .
    container_name: es-node-1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /DATA1:/DATA1/elasticsearch
      - ./config/elasticsearch-node-1.yml:/etc/elasticsearch/elasticsearch.yml
      - ./config/jvm.options-node:/etc/elasticsearch/jvm.options
      - config-es-node-1:/etc/elasticsearch
    networks:
      - elk
  es-node-2:
    build: .
    container_name: es-node-2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /DATA2:/DATA2/elasticsearch
      - ./config/elasticsearch-node-2.yml:/etc/elasticsearch/elasticsearch.yml
      - ./config/jvm.options-node:/etc/elasticsearch/jvm.options
      - config-es-node-2:/etc/elasticsearch
    networks:
      - elk

volumes:
  DATA1:
    driver: local
  DATA2:
    driver: local
  DATA3:
    driver: local
  config-es-master:
    driver: local
  config-es-node-1:
    driver: local
  config-es-node-2:
    driver: local

networks:
  elk:
    driver: bridge
