# Building custom image drupal-bootstrap from Dockerfile in order to activate bootstrap template downloaded in Dockerfile
version: '3'
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    image: drupal-bootstrap
    ports:
      - '8080:80'
    volumes:
      - ./drupal_modules:/var/www/html/modules
      - ./drupal_profiles:/var/www/html/profiles
      - ./drupal_sites:/var/www/html/sites
      - ./drupal_themes:/var/www/html/themes
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'drupal'
    volumes:
      - ./data_db:/var/lib/postgresql/data

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes:
  data_db:
