#In this example nginx is used as proxy, and apache is used as webserver 
version: '3.2'
services:
  proxy:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd
