#In this example nginx is used as proxy, and apache is used as webserver 
version: '3.2'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx
    ports:
      - '8080:80'
  web:
    image: httpd
