version: '2.2'
services:
  master-es:
    build: elasticsearch/
    container_name: es-master
    hostname: es-master
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /DATA0:/DATA0/elasticsearch
      - ./elasticsearch/elasticsearch-master.yml:/etc/elasticsearch/elasticsearch.yml
      - ./elasticsearch/jvm.options-master:/etc/elasticsearch/jvm.options
      - config-es-master:/etc/elasticsearch
    ports:
      - 9200:9200
    networks:
      elk:
        ipv4_address: 172.29.0.2

  node-1-es:
    build: elasticsearch/
    container_name: es-node-1
    hostname: es-node-1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /DATA1:/DATA1/elasticsearch
      - ./elasticsearch/elasticsearch-node-1.yml:/etc/elasticsearch/elasticsearch.yml
      - ./elasticsearch/jvm.options-node:/etc/elasticsearch/jvm.options
      - config-es-node-1:/etc/elasticsearch
    networks:
      elk:
        ipv4_address: 172.29.0.3

  node-2-es:
    build: elasticsearch/
    container_name: es-node-2
    hostname: es-node-2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /DATA2:/DATA2/elasticsearch
      - ./elasticsearch/elasticsearch-node-2.yml:/etc/elasticsearch/elasticsearch.yml
      - ./elasticsearch/jvm.options-node:/etc/elasticsearch/jvm.options
      - config-es-node-2:/etc/elasticsearch
    networks:
      elk:
        ipv4_address: 172.29.0.4

  kibana-es:
    build: kibana/
    container_name: kibana
    hostname: kibana
    volumes:
      - ./kibana/kibana.yml:/etc/kibana/kibana.yml
      - config-kibana:/etc/kibana
    ports:
      - "5601:5601"
    networks:
      elk:
        ipv4_address: 172.29.0.5
    depends_on: 
      - master-es

  logstash-es:
    build: logstash/
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash/logstash.yml:/etc/logstash/logstash.yml
      - ./logstash/pipelines.yml:/etc/logstash/pipeline.yml
      - ./logstash/pipeline:/etc/logstash/conf.d
      - ./logstash/jvm.options:/etc/logstash/jvm.options
      - /DATA1/logstash:/DATA1/logstash
      - config-logstash:/etc/logstash
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      elk:
        ipv4_address: 172.29.0.6
    depends_on:
      - master-es

  cerebro-es:
    build: cerebro/
    container_name: cerebro
    hostname: cerebro
    environment:
      CEREBRO_PORT: 9090
    volumes:
      - config-cerebro:/opt/cerebro/conf
      - ./cerebro/application.conf/:/opt/cerebro/conf/application.conf
    ports: 
      - "9090:9090"
    networks:
      elk:
        ipv4_address: 172.29.0.7
    depends_on: 
      - master-es

  curator-es:
    build: curator/
    container_name: curator
    volumes:
      - ./curator/config:/config
    networks:
      elk:
        ipv4_address: 172.29.0.8
    depends_on: 
      - master-es

volumes:
  config-es-master:
    driver: local
  config-es-node-1:
    driver: local
  config-es-node-2:
    driver: local
  config-kibana:
    driver: local
  config-logstash:
    driver: local
  config-cerebro:
    driver: local

networks:
  elk:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1
